### ISSUE TITLE
Github package uses wrong java version

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#143]
**Describe the bug**

https://github.com/teragrep/rlp_03/blob/d0df8e59b88a6f33beb01f1a821375eec31ee1c5/.github/workflows/upload_release.yaml#L45

**Expected behavior**

Should be 
https://github.com/teragrep/rlp_03/blob/d0df8e59b88a6f33beb01f1a821375eec31ee1c5/.github/workflows/upload_release.yaml#L24
 
**How to reproduce**

 
**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by kortemik** [comment]
all use currently           java-version: 8.0.292+10
