### ISSUE TITLE
Occasional BufferLease terminated issue with PR194

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#199]
**Describe the bug**

Got occasional "BufferLease terminated" exception but after testing I could not reproduce it anymore. It might have been local issue with inconsistent versioning.
 
**Expected behavior**

Works
 
**How to reproduce**

N/A
 
**Screenshots**

 
**Software version**

PR #194

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by kortemik** [comment]
please elaborate on testing, what was being tested and how?

**Comment by StrongestNumber9** [comment]
Used rlp_03 benchmark server test with in development versions of rlp_09 and rlp_10, tried to flood data using rlp_03 client. Most likely issue with 0.0.1-SNAPSHOT and 0.0.2-SNAPSHOTs being used and using proper version

**Comment by kortemik** [comment]
reopen if necessary, can not reproduce, may be that rlp_09 or rlp_10 held reference to an relp frame that was already sent and closed.
