### ISSUE TITLE
Returning boolean from a "manipulator" method.

### ISSUE THREAD

**Issue by kortemik** [teragrep/rlp_03#206]
Returning boolean from a "manipulator" method.

_Originally posted by @51-code in https://github.com/teragrep/rlp_03/pull/189#discussion_r1642209293_

**Comment by kortemik** [comment]
@eemhu please throw some comments

**Comment by eemhu** [comment]
Perhaps the `FrameDelegationClock` could be decorated as `InterestedFrameDelegationClock`, with `boolean interestedInData()` method returning `true`, while the original `FrameDelegationClock` would return `false`

**Comment by kortemik** [comment]
see pr #209
