### ISSUE TITLE
Coverity: Lock not released on all paths In com.​teragrep.​rlp_03.​Status.​complete()

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#64]
**Describe the bug**

In com.​teragrep.​rlp_03.​Status.​complete(): This method acquires a JSR-166 (java.util.concurrent) lock, but does not release it on all exception paths out of the method. ([From SpotBugs description](https://scan3.scan.coverity.com/doc/en/spotbugs/sb_checker_ref.html#FB.UL_UNRELEASED_LOCK_EXCEPTION_PATH))

Coverity says

```sh
22    void complete() {
CID 436390: (#1 of 1): UL: Lock not released on all paths (FB.UL_UNRELEASED_LOCK_EXCEPTION_PATH)
1. defect: com.teragrep.rlp_03.Status.complete() does not release lock on all exception paths.
23        lock.lock();
24        done.set(true);
25        pending.signal();
26        lock.unlock();
27    }
```
 
**Expected behavior**

 
**How to reproduce**

 
**Screenshots**

 
**Software version**

 
https://github.com/teragrep/rlp_03/blob/60da3293c6f66191920cd333f982f802ab0658b7/src/main/java/com/teragrep/rlp_03/Status.java#L22-L27

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by kortemik** [comment]
fix with
```
lock.lock(); try { /* existing code */ } finally { lock.unlock(); }
```
