### ISSUE TITLE
Coverity: Resource leak on an exceptional path In com.​teragrep.​rlp_03.​SocketPoll.​processAccept

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#67]
**Describe the bug**

The system resource will not be reclaimed and reused, reducing the future availability of the resource.

In com.​teragrep.​rlp_03.​SocketPoll.​processAccept(java.​nio.​channels.​ServerSocketChannel, java.​nio.​channels.​SelectionKey): Leak of a system resource on an exception path (probably error handling) ([CWE-404](http://cwe.mitre.org/data/definitions/404.html))

Coverity says

```sh

 98    private void processAccept(ServerSocketChannel serverSocketChannel, SelectionKey selectionKey) throws IOException {
      1. Condition selectionKey.isAcceptable(), taking true branch.
 99        if (selectionKey.isAcceptable()) {
100            // create the client socket for a newly received connection
      2. alloc_fn: A new resource is returned from allocation method accept.
      3. var_assign: Assigning: clientSocketChannel = resource returned from serverSocketChannel.accept().
101            SocketChannel clientSocketChannel = serverSocketChannel.accept();
102
      4. Condition com.teragrep.rlp_03.SocketPoll.LOGGER.isDebugEnabled(), taking true branch.
103            if (LOGGER.isDebugEnabled()) {
      5. Throwing java.io.IOException (or subclass) from call to getLocalAddress; exiting method with uncaught exception.
     
CID 436388: (#1 of 1): Resource leak on an exceptional path (RESOURCE_LEAK)
6. leaked_resource: Variable clientSocketChannel going out of scope leaks the resource it refers to.
104                LOGGER.debug("ServerSocket <{}> accepting ClientSocket <{}> ", serverSocketChannel.getLocalAddress(), clientSocketChannel.getRemoteAddress());
105            }
```
 
**Expected behavior**

 
**How to reproduce**

 
**Screenshots**

 
**Software version**

 https://github.com/teragrep/rlp_03/blob/60da3293c6f66191920cd333f982f802ab0658b7/src/main/java/com/teragrep/rlp_03/SocketPoll.java#L98-L108

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by kortemik** [comment]
fixed in #99
