### ISSUE TITLE
Remove or implement commented out code in CommandFunction.java

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/rlp_03#79]
**Description**

Clean up code where necessary
 
**Use case or motivation behind the feature request**

Commented out code is burden from code maintenance point of view
 
**Related issues**

 
**Additional context**

https://github.com/teragrep/rlp_03/blob/42a40746da1263dcba32d69bbfbd4a7c6cfbfbf2/src/main/java/com/teragrep/rlp_03/context/frame/function/CommandFunction.java#L15-L36

**Comment by eemhu** [comment]
@kortemik is this something to implement or just remove?

**Comment by kortemik** [comment]
fixed in #94
